package com.fuwei.selecthappylocation.event;

/**
 * Created by collin on 2015-10-02.
 */
public enum Event {
    EVENT_LOGIN_SUCCESS, EVENT_LOGIN_FAIL,
    EVENT_GET_BIRTHDAY_SELECT_SUCCESS, EVENT_GET_BIRTHDAY_SELECT_FAIL,
    EVENT_GET_MY_SELECTION_SUCCESS, EVENT_GET_MY_SELECTION_FAIL,
    EVENT_GET_SELECTION_DETAIL_SUCCESS, EVENT_GET_SELECTION_DETAIL_FAIL,
}
